create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 2 and 120),
  score integer not null check (score between 0 and 16),
  time_ms integer not null check (time_ms >= 0),
  created_at timestamptz not null default now()
);

alter table public.quiz_results enable row level security;

drop policy if exists "Anyone can read quiz results" on public.quiz_results;
create policy "Anyone can read quiz results"
  on public.quiz_results for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can submit quiz results" on public.quiz_results;
create policy "Anyone can submit quiz results"
  on public.quiz_results for insert
  to anon, authenticated
  with check (true);
